apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpbagv3q4-java-springboot
  janus-idp.io/tekton: hpbagv3q4-java-springboot
  backstage.io/kubernetes-id: hpbagv3q4-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hpbagv3q4-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
